EDA for d3.js

In [141]:
import pandas as pd
video_game = pd.read_csv("./datasets/Video Game Sales with Ratings.csv")
print(video_game.shape)
video_game.head()

(16719, 16)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [142]:
video_game["Critic_Count"]

0        51.0
1         NaN
2        73.0
3        73.0
4         NaN
         ...
16714     NaN
16715     NaN
16716     NaN
16717     NaN
16718     NaN
Name: Critic_Count, Length: 16719, dtype: float64

In [143]:
video_game.dropna(inplace=True)
print(video_game.shape)
video_game.tail()

(6825, 16)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
16667,E.T. The Extra-Terrestrial,GBA,2001.0,Action,NewKidCo,0.01,0.00,0.0,0.0,0.01,46.0,4.0,2.4,21.0,Fluid Studios,E
16677,Mortal Kombat: Deadly Alliance,GBA,2002.0,Fighting,Midway Games,0.01,0.00,0.0,0.0,0.01,81.0,12.0,8.8,9.0,Criterion Games,M
16696,Metal Gear Solid V: Ground Zeroes,PC,2014.0,Action,Konami Digital Entertainment,0.00,0.01,0.0,0.0,0.01,80.0,20.0,7.6,412.0,Kojima Productions,M
16700,Breach,PC,2011.0,Shooter,Destineer,0.01,0.00,0.0,0.0,0.01,61.0,12.0,5.8,43.0,Atomic Games,T
16706,STORM: Frontline Nation,PC,2011.0,Strategy,Unknown,0.00,0.01,0.0,0.0,0.01,60.0,12.0,7.2,13.0,SimBin,E10+

## 圆图

In [139]:
sales_counts = video_game["Global_Sales"].value_counts().sort_values(ascending=True)

# 获取排名前十的 Global_Sales 的名称列表
top_50_sales = list(sales_counts.head(50).index)

sales_topdf = video_game[video_game['Global_Sales'].isin(top_50_sales)]
sales_topdf = sales_topdf.reset_index(drop=True)


sales_topdf.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
1,Wii Play,Wii,2006.0,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,58.0,41.0,6.6,129.0,Nintendo,E
2,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.44,6.94,4.70,2.24,28.32,87.0,80.0,8.4,594.0,Nintendo,E
3,Mario Kart DS,DS,2005.0,Racing,Nintendo,9.71,7.47,4.13,1.90,23.21,91.0,64.0,8.6,464.0,Nintendo,E
4,Wii Fit,Wii,2007.0,Sports,Nintendo,8.92,8.03,3.60,2.15,22.70,80.0,63.0,7.7,146.0,Nintendo,E

In [155]:
sales_topdf["Critic_Score"]=sales_topdf["Critic_Score"]/10
sales_topdf["Critic_Score"]

0     8.0
1     5.8
2     8.7
3     9.1
4     8.0
5     6.1
6     8.0
7     9.7
8     9.5
9     7.7
10    9.7
11    9.5
12    7.7
13    9.5
14    8.8
15    8.7
16    8.3
17    8.3
18    9.4
19    8.8
20    9.7
21    9.3
22    8.8
23    8.6
24    9.8
25    9.6
26    9.0
27    8.4
28    9.4
29    9.8
30    7.3
31    7.4
32    7.8
33    9.1
34    9.2
35    8.7
36    9.3
37    7.4
38    7.1
39    9.4
40    8.8
41    7.2
42    9.6
43    8.2
44    9.5
45    6.8
46    8.8
47    9.7
48    9.3
49    7.5
Name: Critic_Score, dtype: float64

In [157]:
sales_topdf.to_csv("sales_topdf.csv")

## top publisher

In [144]:
# 对 publisher 列进行统计并排序
publisher_counts = video_game["Publisher"].value_counts().sort_values(ascending=False)

# 获取排名前十的 publisher 的名称列表
top_8_publishers = list(publisher_counts.head(8).index)

print(top_8_publishers)

['Electronic Arts', 'Ubisoft', 'Activision', 'Sony Computer Entertainment', 'THQ', 'Nintendo', 'Sega', 'Take-Two Interactive']

In [145]:
# 筛选出在前8列表中的行
video_game = video_game[video_game['Publisher'].isin(top_8_publishers)]
print(video_game.shape)

(3403, 16)

## developer top8

In [146]:
developer_counts = video_game["Developer"].value_counts().sort_values(ascending=False)
top_8_developer = list(developer_counts.head(8).index)

print(top_8_developer)

['EA Canada', 'EA Sports', 'Ubisoft', 'Ubisoft Montreal', 'EA Tiburon', 'Nintendo', 'Electronic Arts', 'Visual Concepts']

In [147]:
video_game = video_game[video_game['Developer'].isin(top_8_developer)]
print(video_game.shape)

(763, 16)

## platform top8

In [148]:
platform_counts = video_game["Platform"].value_counts().sort_values(ascending=False)
top_8_platform = list(platform_counts.head(8).index)
print(top_8_platform)

['X360', 'PS2', 'PS3', 'XB', 'GC', 'Wii', 'PC', 'PSP']

In [149]:
video_game = video_game[video_game['Platform'].isin(top_8_platform)]
print(video_game.shape)

(606, 16)

## genre

In [150]:
video_game = pd.DataFrame(video_game)
video_game = video_game.reset_index(drop=True)
video_game.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
2,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
3,Wii Play,Wii,2006.0,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,58.0,41.0,6.6,129.0,Nintendo,E
4,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.44,6.94,4.70,2.24,28.32,87.0,80.0,8.4,594.0,Nintendo,E

In [151]:
video_game['Category'] = 'Others'
for i in range(len(video_game)):
    if video_game['Genre'][i] == 'Shooter' or video_game['Genre'][i] == 'Action':
        video_game['Category'][i] = 'Action'
    elif video_game['Genre'][i] == 'Simulation' or video_game['Genre'][i] == 'Strategy' or video_game['Genre'][i] == 'Role-Playing':
        video_game['Category'][i] = 'Strategy'
    elif video_game['Genre'][i] == 'Puzzle' or video_game['Genre'][i] == 'Misc':
        video_game['Category'][i] = 'Puzzle'
    elif video_game['Genre'][i] == 'Sports' or video_game['Genre'][i] == 'Racing' or video_game['Genre'][i] == 'Fighting':
        video_game['Category'][i] = 'Sports'
    elif video_game['Genre'][i] == 'Adventure' or video_game['Genre'][i] == 'Platform':
        video_game['Category'][i] = 'Adventure'

video_game.head()

/var/folders/dv/x_66hhts063355xh4tw6jl6w0000gn/T/ipykernel_2111/1039966122.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/dv/x_66hhts063355xh4tw6jl6w0000gn/T/ipykernel_2111/1039966122.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/dv/x_66hhts063355xh4tw6jl6w0000gn/T/ipykernel_2111/1039966122.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/dv/x_66hhts063355xh4tw6jl6w0000gn/T/ipykernel_2111/1039966122.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/dv/x_66hhts063355xh4tw6jl6w0000gn/T/ipykernel_2111/1039966122.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Category
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E,Sports
1,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,Sports
2,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E,Sports
3,Wii Play,Wii,2006.0,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,58.0,41.0,6.6,129.0,Nintendo,E,Puzzle
4,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.44,6.94,4.70,2.24,28.32,87.0,80.0,8.4,594.0,Nintendo,E,Adventure

In [152]:
video_game.shape

(606, 17)

In [153]:

video_game.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Category
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E,Sports
1,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,Sports
2,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E,Sports
3,Wii Play,Wii,2006.0,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,58.0,41.0,6.6,129.0,Nintendo,E,Puzzle
4,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.44,6.94,4.70,2.24,28.32,87.0,80.0,8.4,594.0,Nintendo,E,Adventure

In [154]:
video_game.to_csv("cleaned_video_game.csv")

In [125]:
df=pd.read_csv('/Users/xiangxin/2023-anly503-xx123/ANLY503_FINAL_PROJECT/cleaned_video_game.csv')
df

,Unnamed: 0,Platform,Genre,Publisher,Critic_Score,User_Score,Rating,Cat
0,0,PS2,Racing,Sony Computer Entertainment,95.0,8.4,E,Sports
1,1,X360,Shooter,Activision,88.0,3.4,M,Action
2,2,X360,Shooter,Activision,87.0,6.3,M,Action
3,3,PS3,Shooter,Activision,83.0,5.3,M,Action
4,4,X360,Shooter,Activision,83.0,4.8,M,Action
...,...,...,...,...,...,...,...,...
1553,1553,PS2,Shooter,Activision,70.0,9.2,E10+,Action
1554,1554,PC,Action,Ubisoft,79.0,6.8,E,Action
1555,1555,PC,Racing,THQ,61.0,5.0,T,Sports
1556,1556,PC,Action,Activision,58.0,8.0,E10+,Action
1557,1557,PC,Action,Activision,78.0,7.9,T,Action

## steam data eda

In [186]:
steam_df = pd.read_csv("./datasets/steam.csv")
mask = ~steam_df['genres'].str.contains(';')
mask
# Apply the mask to the DataFrame to keep only the rows where 'genres' does not contain ';'
steam_df = steam_df[mask]

In [187]:
print(steam_df.shape)
steam_df.head()

(4043, 18)

,appid,name,release_date,english,developer,publisher,platforms,required_age,categories,genres,steamspy_tags,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price
0,10,Counter-Strike,2000-11-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,124534,3339,17612,317,10000000-20000000,7.19
1,20,Team Fortress Classic,1999-04-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,3318,633,277,62,5000000-10000000,3.99
2,30,Day of Defeat,2003-05-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Valve Anti-Cheat enabled,Action,FPS;World War II;Multiplayer,0,3416,398,187,34,5000000-10000000,3.99
3,40,Deathmatch Classic,2001-06-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,1273,267,258,184,5000000-10000000,3.99
4,50,Half-Life: Opposing Force,1999-11-01,1,Gearbox Software,Valve,windows;mac;linux,0,Single-player;Multi-player;Valve Anti-Cheat en...,Action,FPS;Action;Sci-fi,0,5250,288,624,415,5000000-10000000,3.99

## top 8 genres

In [193]:
ge_counts = steam_df["genres"].value_counts().sort_values(ascending=False)
top_10_ge = list(ge_counts.head(10).index)
print(top_10_ge)

['Action', 'Indie', 'Casual', 'Adventure', 'Strategy', 'Simulation', 'RPG', 'Racing', 'Sports', 'Utilities']

In [194]:
steam_df = steam_df[steam_df['genres'].isin(top_10_ge)]
steam_df = steam_df.reset_index(drop=True)
print(steam_df.shape)
steam_df.head()

(3973, 19)

,appid,name,release_date,english,developer,publisher,platforms,required_age,categories,genres,steamspy_tags,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price,price_range
0,10,Counter-Strike,2000-11-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,124534,3339,17612,317,10000000-20000000,7.19,1-20 dollars
1,20,Team Fortress Classic,1999-04-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,3318,633,277,62,5000000-10000000,3.99,1-20 dollars
2,30,Day of Defeat,2003-05-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Valve Anti-Cheat enabled,Action,FPS;World War II;Multiplayer,0,3416,398,187,34,5000000-10000000,3.99,1-20 dollars
3,40,Deathmatch Classic,2001-06-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,1273,267,258,184,5000000-10000000,3.99,1-20 dollars
4,50,Half-Life: Opposing Force,1999-11-01,1,Gearbox Software,Valve,windows;mac;linux,0,Single-player;Multi-player;Valve Anti-Cheat en...,Action,FPS;Action;Sci-fi,0,5250,288,624,415,5000000-10000000,3.99,1-20 dollars

In [188]:
steam_df["price_range"]="na"
for i in range(len(steam_df)):
    if steam_df['price'][i] == 0 :
        steam_df['price_range'][i] = 'free'
    elif steam_df['price'][i] >0 and steam_df['price'][i]<=20:
        steam_df['price_range'][i] = '1-20 dollars'
    elif steam_df['price'][i] >20 and steam_df['price'][i]<=50:
        steam_df['price_range'][i] = '20-50 dollars'
    elif steam_df['price'][i] >50 and steam_df['price'][i]<=500:
        steam_df['price_range'][i] = '50-500 dollars'

steam_df.head()

/var/folders/dv/x_66hhts063355xh4tw6jl6w0000gn/T/ipykernel_2111/1591395118.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/dv/x_66hhts063355xh4tw6jl6w0000gn/T/ipykernel_2111/1591395118.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

KeyError: 19

In [195]:
steam_df.to_csv("steam_df.csv")

In [185]:
print(steam_df["price_range"])

0        1-20 dollars
1        1-20 dollars
2        1-20 dollars
3        1-20 dollars
4        1-20 dollars
             ...
27037              na
27040              na
27047              na
27061              na
27069              na
Name: price_range, Length: 4043, dtype: object